version: '3.8'

services:
  
  db:
    build:
      dockerfile: Dockerfiles/postgres.Dockerfile
      context: .
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Users
    network_mode: host

  admin:

    image: dpage/pgadmin4
    container_name: pgAdmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345

    network_mode: host 

  
  nginx:

    build:
      dockerfile: Dockerfiles/nginx.Dockerfile
      context: .
    container_name: nginx
    restart: always

    ports:
    - 5050:80

    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf

  ngrok:
    image: ngrok/ngrok:latest
    command:
    - "start"
    - "--all"
    - "--config"
    - "/etc/ngrok.yml"
    volumes:
    - ./ngrok.yml:/etc/ngrok.yml
    network_mode: host

    depends_on:
    - nginx
