version: '3.8'

services:
  
  db:
    build:
      dockerfile: Dockerfiles/postgres.Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Users
    network_mode: host

  admin:

    image: dpage/pgadmin4
    container_name: pgAdmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345

    network_mode: host 

    depends_on:
     - db
