
services:
    
    python:
      build:
        context: .

      network_mode: host


    ngrok:
      image: ngrok/ngrok
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - ./ngrok.yml:/etc/ngrok.yml

      network_mode: host
