# Generated by Django 5.0.2 on 2024-03-05 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
