# Generated by Django 5.0.4 on 2024-04-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usu', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.TextField(max_length=255),
        ),
    ]
